# Generated by Django 3.2.7 on 2021-10-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.TextField(default=1, max_length=9999),
            preserve_default=False,
        ),
    ]
