# Generated by Django 3.2.8 on 2021-10-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_city_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='description',
            field=models.TextField(default=1, max_length=9999),
            preserve_default=False,
        ),
    ]
