# Generated by Django 3.2.8 on 2021-10-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_park_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
