# Generated by Django 3.2.8 on 2021-10-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_city_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.ImageField(upload_to=None),
        ),
        migrations.AlterField(
            model_name='park',
            name='image',
            field=models.CharField(max_length=9999),
        ),
        migrations.AlterField(
            model_name='person',
            name='display_name',
            field=models.CharField(default='EnjoyerOfParks', max_length=256),
        ),
        migrations.AlterField(
            model_name='person',
            name='location',
            field=models.CharField(default='Some Park', max_length=256),
        ),
    ]
