# Generated by Django 3.2.8 on 2021-10-28 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20211027_0410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='park',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='park',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parks', to='main_app.city'),
        ),
    ]
